# AndroidX + Jetifier (required together)
android.useAndroidX=true
android.enableJetifier=true

# JDK 17 for Gradle Daemon (match your install path)
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.16.8-hotspot

# (optional but nice)
kotlin.code.style=official
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
